### ISSUE TITLE
matplotlib set_clim deprecation

### ISSUE THREAD

**Issue by EgorVe** [juanmcloaiza/GisansExplorer#1]
Hi Juan 
when running the code i get a warning:
The set_clim function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use ScalarMappable.set_clim instead

**Comment by juanmcloaiza** [comment]
Hi Egor, 

thanks for reporting this. The issue should be now fixed in the develop branch. 
(https://github.com/juanmcloaiza/NeutronDataViewer/commit/c4029252dbda75d51bafe6a3a1a479ffb8cb9419)

Cheers,
Juan
